### ISSUE TITLE
Add information about how to handle write errors

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb.com#100]
See this thread: https://twitter.com/tisba/status/618416895272845312

**Comment by beckettsean** [comment]
Add a note about writes with explicit timestamps being idempotent to the troubleshooting page and to the writing data guide.

**Comment by beckettsean** [comment]
Ideally we should find out what errors are returned for most classes of bad writes and describe how to fix them.

**Comment by beckettsean** [comment]
https://github.com/influxdb/influxdb/issues/4986 is one error we need to document.

500s are another.

Type mismatch is somewhat obvious but should be documented.
