### ISSUE TITLE
Give UDP examples of line protocol

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#102]
Need to document UDP in general.

**Comment by chetandhembre** [comment]
Can you guys just give me some pointer how to use UDP for line protocol in any language. I will be super helpful. My work is stuck due to this. please help !!

**Comment by beckettsean** [comment]
@chetandhembre unfortunately I know nothing about it yet, try emailing influxdb@googlegroups.com, there are lots of community members more knowledgable about UDP than the support team here at InfluxDB.

**Comment by chetandhembre** [comment]
Hey i asked arround on IRC and found how to do it. I created node.js module which implement line-protocol please take look. https://github.com/chetandhembre/node-influxdb-line-protocol. 
feedbacks are welcome :)

**Comment by beckettsean** [comment]
```
[udp]
  enabled = true
  bind-address = ":8086"
  database = "foo"
  batch-size = 1000
  batch-timeout = “1s”


To write, just send newline separated line protocol over UDP.  Can send one point at a time (not very performant) or send batches.

$ echo "cpu value=1"> /dev/udp/localhost/8086
$ echo "select * from cpu" | influx -database foo
Connected to http://localhost:8086 version 0.9
InfluxDB shell 0.9
name: cpu
---------
time                value
2015-08-06T15:44:58.544559824Z    1
```

**Comment by beckettsean** [comment]
@mjdesa Please add a new page called "UDP" to the write section. Document the config options, give an example write of a single point and multiple points. Not sure there's much else to document just yet.
