### ISSUE TITLE
create RSS feed for blog posts

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#108]

**Comment by gunnaraasen** [comment]
The RSS feed is https://influxdb.com/index.xml. It seems like the current CloudFront configuration is causing auto-discovery problems for feed readers. I'll leave this open to confirm the feed is auto-discoverable once the Cloudfront stuff is fixed.

**Comment by gunnaraasen** [comment]
RSS feed auto-discovery appears to work as expected since https://github.com/influxdb/influxdb.com/commit/d6b3773fb7e4300e52b4e44b2a67d4616671b85d was made.
