### ISSUE TITLE
test behavior of every function and math operator against each data type

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#112]
Inspired by https://github.com/influxdb/influxdb/issues/3240#issuecomment-119742593

Let's find out and document whether you can use boolean values with MAX or strings with LAST, etc. We should check `float`, `int`, `string`, and `bool` against every valid function (e.g. `derivative`, `count`) and every valid mathematical operator (e.g. `+`, `*`)

**Comment by mjdesa** [comment]
`min()`, `max()`  on boolean or string values returns 0
    		       on float they work appropriately
	    	       on ints they typecast to float then back to int

 `mean()`, `median`, `stddev()	`  on boolean or string values returns 0
    	       		      on float and int they work appropriately

`percentile()` on boolean, string, or integer values yield empty result
                    on floats they work appropriately

`last()`, `first()`,`distinct()` behave as expected for all values

`derivative()` doesn’t currently work and yields error [3355](https://github.com/influxdb/influxdb/issues/3355)
