### ISSUE TITLE
new page: document valid mathematical operators

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#113]
Investigate and document the behavior of `+`, `-`, `/`, `*`, `=`, `>`, `<`, `<=`, `>=`, `%`, `^`, `(`, `)`, and am I missing any?

**Comment by beckettsean** [comment]
`!=`. For booleans presumably `&`, `|`, `!&`?, `!|`?, `AND`, `OR, `NAND`, `XOR`, `NOR`, etc.

**Comment by mjdesa** [comment]
`+` works as expected for floats. **Doesn't work for integers yet, currently it yields empty results***

`-` works as expected for floats. **Doesn't work for integers yet, currently it yields empty results***

`/` works as expected for floats. **Doesn't work for integers yet, currently it yields empty results***

`*` works as expected for floats. **Doesn't work for integers yet, currently it yields empty results***

`=`,`!=`,`<`,`>`,`<=`,`>=` all yield empty results for all types

`%`, `^` yield a parse error

`&`,`|`,`!|`,` yield parse error

`AND`, `OR` don't behave as mathematical operators and simply yield empty results

`NAND`, `XOR`, `NOR` yield parse error

**Comment by mjdesa** [comment]
@beckettsean should I include also using mathematical operators with functions on this page?

**Comment by beckettsean** [comment]
Yes, if using a function differs or is a superset of using operators with field values or numbers.

**Comment by mjdesa** [comment]
@beckettsean any preference as to which section this should go in?

**Comment by beckettsean** [comment]
I'd say query_language

**Comment by mjdesa** [comment]
The [math ops](https://github.com/influxdb/influxdb.com/tree/math-ops) branch is the start of page.
