### ISSUE TITLE
Logging boolean datapoints

### ISSUE THREAD

**Issue by dawbs** [influxdb/influxdb.com#114]
On the write spec page:
https://influxdb.com/docs/v0.9/write_protocols/write_syntax.html

Format is listed as:
"boolean values are t, T, true, True, or TRUE for TRUE, and f, F, false, False, or FALSE for FALSE"

However boolean value of "True" returns error "invalid boolean". The exact same entry with lowercase "true" works

Is the spec or the implementation wrong?

**Comment by dawbs** [comment]
To clarify, this also appears to be a regression in 0.9.1

**Comment by jwilder** [comment]
This is a regression and should be fixed by https://github.com/influxdb/influxdb/pull/3307
