### ISSUE TITLE
make sure all files are linked in nav bar, and any others are deleted

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#118]
For instance, https://influxdb.com/docs/v0.9/query_language/querying_data.html is a dead page but is still in the repo.

Note that `Troubleshooting` is an exception, as it's not yet ready for release but is checked into Master.

**Comment by gunnaraasen** [comment]
I've [removed](https://github.com/influxdb/influxdb.com/commit/0a666ee204d2203d8f63dbb9a292fce82ee6ecd8) the orphaned querying data page. Still need to check the rest of the files.

**Comment by beckettsean** [comment]
We linked troubleshooting in via #128, so I think we're good for now.

**Comment by beckettsean** [comment]
Re-opening, as `data sources` are still not in the right nav bar.

**Comment by beckettsean** [comment]
Closing for now in favor of https://github.com/influxdb/influxdb.com/issues/290
