### ISSUE TITLE
Document downsampling with tags

### ISSUE THREAD

**Issue by markusr** [influxdb/influxdb.com#120]
As I understand to preserve all tags you have to put 
```
, *
```
at the end of the query.

```
CREATE CONTINUOUS QUERY event_counts_per_10m_by_type ON mydb BEGIN
  SELECT COUNT(type) INTO typeCount_10m_byType FROM events GROUP BY time(10m), *
END
```
See: https://github.com/influxdb/influxdb/issues/3052

**Comment by beckettsean** [comment]
committed change to https://github.com/influxdb/influxdb.com/blob/master/content/docs/v0.9/query_language/continuous_queries.md to make this more clear.
