### ISSUE TITLE
Document `chunk_size` URL parameter on query endpoint

### ISSUE THREAD

**Issue by gunnaraasen** [influxdb/influxdb.com#121]
We should document the `chunk_size` parameter for the `/query` endpoint on the [API endpoint](https://influxdb.com/docs/v0.9/concepts/api.html) and [data exploration](https://influxdb.com/docs/v0.9/query_language/data_exploration.html) pages. 

https://github.com/influxdb/influxdb/blob/master/services/httpd/handler.go#L216

Also see influxdb/influxdb#3242.

**Comment by mjdesa** [comment]
closed by [148](https://github.com/influxdb/influxdb.com/pull/148)
