### ISSUE TITLE
document basic installation for AWS

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#122]
Include getting influxdb, telegraf, chronograf running, as well as a cluster of 3+ nodes with ELB in front. 

Assume all in the same AZ.
Assume for now all same instance type and OS
EBS for storage? What options?

**Comment by beckettsean** [comment]
See https://github.com/influxdb/influxdb/issues/2377 for more details on the use case and the ultimate direction we want to head with this. Auto-discovery should be handled by ELB (https://github.com/influxdb/influxdb/issues/2966)

**Comment by beckettsean** [comment]
Add as a linkable section on the installation page, for now.

**Comment by mjdesa** [comment]
@beckettsean should it live anywhere on the sidebar?

**Comment by beckettsean** [comment]
I think it depends on the length. If it's one to three paragraphs I say stick it on the installation page at the bottom. If it's longer than that, put it in the Administration section on the sidebar.
