### ISSUE TITLE
Update all occurrences of `SHOW RETENTION POLICIES`

### ISSUE THREAD

**Issue by gunnaraasen** [influxdb/influxdb.com#125]
As of https://github.com/influxdb/influxdb/pull/3345, the syntax for displaying all retention policies is

```
SHOW RETENTION POLICIES ON mydb
```

This needs to be update in the docs from the old syntax, which only worked without `ON`, e.g. `SHOW RETENTION POLICIES mydb`. Also needs to include a disclaimer for people upgrading from versions 0.9.0 and 0.9.1.

**Comment by beckettsean** [comment]
partial fix in #138, just need to put in a disclaimer (most likely a new page describing the changes from 0.9.1 to 0.9.2)

**Comment by gunnaraasen** [comment]
Would the [release notes page](https://github.com/influxdb/influxdb.com/blob/master/content/docs/v0.9/about/release_notes.md) be a good place for that disclaimer?

**Comment by beckettsean** [comment]
Yeah, perfect. I'll make a PR later today.

**Comment by beckettsean** [comment]
fixed by @mjdesa in #147. Closing
