### ISSUE TITLE
How to make Continuous Query inherit tags from the source time series?

### ISSUE THREAD

**Issue by junmipan** [influxdb/influxdb.com#126]
The instructions in "https://influxdb.com/docs/v0.9/query_language/continuous_queries.html" do not describe how to inherit tags from the source time series when creating continuous queries.

Can you provide more insight?  Thanks.

Junmin Pan
Cisco Systems, Inc.

**Comment by gunnaraasen** [comment]
Adding a `GROUP BY time(x), *` will make the CQ target measurement inherit all tags and `GROUP BY time(x), tag_key1, tag_key2` will make the CQ target measurement inherit specific tag keys. Retaining tags is behavior that needs to be documented.

**Comment by beckettsean** [comment]
Fixed by https://github.com/influxdb/influxdb.com/commit/8cea6a9
