### ISSUE TITLE
Missing raw data field value specification

### ISSUE THREAD

**Issue by xkrt** [influxdb/influxdb.com#129]
Hi,

In [Writing Data](https://influxdb.com/docs/v0.9/guides/writing_data.html), in "Schemaless Design" paragraph:
> field values may be integers, floats, strings, booleans, or **raw bytes**

But in [Line Protocol](https://influxdb.com/docs/v0.9/write_protocols/line.html) there no *raw bytes* specification.

**Comment by beckettsean** [comment]
Thanks, @xkrt, I think that's a legacy type that we should remove from the docs. I'll verify with the core team.

@jwilder does the line protocol support raw bytes?

**Comment by otoolep** [comment]
It does not. @pauldix asked that we support this when I was working on the write path many weeks ago. I'm sure it's still a requested feature.

**Comment by beckettsean** [comment]
Closed by #133. We will add it back if/when support for them returns.

Thanks @xkrt for the report!
