### ISSUE TITLE
Update aggregate_functions and include in new site

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#13]
https://github.com/influxdb/influxdb.com/blob/master/content/docs/v0.9/query_language/aggregate_functions.md is out of date and should be replaced with https://github.com/influxdb/influxdb.org/blob/master/source/docs/v0.9/query_language/aggregate_functions.md 

The links in the navigation are missing. The Aggregate Functions link needs to be added back to the Query Language section.

**Comment by gunnaraasen** [comment]
Aggregate functions page and links are back in.
