### ISSUE TITLE
Document WAL tuning parameters

### ISSUE THREAD

**Issue by gunnaraasen** [influxdb/influxdb.com#134]
Explain the WAL parameters. See https://github.com/influxdb/influxdb/pull/3298.

**Comment by beckettsean** [comment]
@pauldix @otoolep what PRs or other docs should we look at to properly document the WAL tuning stuff?

**Comment by pauldix** [comment]
@beckettsean hold off on any WAL documentation until I finish my PR later this week. All of that stuff is about to change.

**Comment by beckettsean** [comment]
@pauldix what do we need to know about the WAL tuning parameters now? I don't want to give advice on how to use them yet, but I do want to list them, what they are called, what are valid settings, and vaguely those settings do.

**Comment by pauldix** [comment]
The example config should have all the information you need: https://github.com/influxdb/influxdb/blob/master/etc/config.sample.toml#L46-L68

**Comment by beckettsean** [comment]
WAL has changed a lot, will wait for things to settle before we document.

**Comment by jackzampolin** [comment]
Addressed by https://github.com/influxdb/influxdb.com/pull/325

**Comment by beckettsean** [comment]
closed by #325
