### ISSUE TITLE
Line protocol specification questions

### ISSUE THREAD

**Issue by shawjef3** [influxdb/influxdb.com#135]
I'm writing a UDP client for InfluxDB 0.9. The line protocol specification leaves me with these questions:

What is the character encoding algorithm?
Can tag keys, tag values, or field names be empty?
Can tag keys, tag values, or field names contain '='? If so, how is it escaped?
The spec says that tag values should not be surrounded in quotes. Does this mean they can contain quotes? How about the tag keys or field names?

Jeff

**Comment by gunnaraasen** [comment]
There's a more detailed line protocol spec [here](https://github.com/influxdb/influxdb/blob/master/tsdb/README.md).

The actually implementation is [here](https://github.com/influxdb/influxdb/blob/master/tsdb/points.go#L139).

> What is the character encoding algorithm?

InfluxDB is written in Go, which uses UTF-8 encoding.

> Can tag keys, tag values, or field names be empty?

No, tag and field keys and values cannot be empty. This is _not_ valid, `cpu,tag=,=value =1.0`.

> Can tag keys, tag values, or field names contain '='? If so, how is it escaped?

Yes, they can be backslash escaped using `\`. e.g. `cpu,a\=host=1` will create a tag key `a=host`.

> The spec says that tag values should not be surrounded in quotes. Does this mean they can contain quotes? How about the tag keys or field names?

Yes, measurements, tag keys and values, and field keys can all contain backslash escaped quotes. The following is a valid line protocol point,

`cpu\=main,tag\=bar=value\=foo name\=bar=1.0`

All of these things can be better explained in the docs so leaving this open.

**Comment by shawjef3** [comment]
Can string field values contain newlines? Possibly escaped?

**Comment by beckettsean** [comment]
@shawjef3 Strings for measurement name, tag key, tag value, or field key would need to have the newline escaped with backslash. Strings that are field values should be double-quoted, and newlines within the double quotes should be fine.

**Comment by beckettsean** [comment]
> Yes, measurements, tag keys and values, and field keys can all contain backslash escaped quotes. The following is a valid line protocol point,

Minor correction to what @gunnaraasen said. If the string is part of a measurement name, tag key, tag value, or field key (the things that are always strings) then single and double quotes can be included without escaping. The parser only looks for comma, equals, backslash, and whitespace and treats everything else as part of the string. For field values, which can be int or float or bool or string, it's the act of double-quoting the value that makes it parse as a string. Therefore double-quotes within the string need to be escaped with backslash. Single quotes shouldn't need it.

Note that I haven't recently verified each of these statements but they should be true. If not, please open a bug report.
