### ISSUE TITLE
remove all references to DUMP in the docs

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#143]
@pauldix is there any backup/restore functionality right now or should we just remove all hints of that?

**Comment by pauldix** [comment]
There is backup/restore so leave that in for now. Can someone from your team test to verify?

**Comment by beckettsean** [comment]
Okay, so this page is probably correct: https://influxdb.com/docs/v0.9/administration/backup_and_restore.html, but any reference to `dump` is not. Does that sound right, @pauldix?

**Comment by pauldix** [comment]
@beckettsean yep

**Comment by beckettsean** [comment]
Cool. @mjdesa is verifying the backup page is correct. I'm working on removing `dump`.

**Comment by beckettsean** [comment]
#146 ready for a +1. Updated https://github.com/influxdb/influxdb/issues/3235 to get it removed from the CLI help output.

**Comment by beckettsean** [comment]
https://github.com/influxdb/influxdb/pull/3453 to fix https://github.com/influxdb/influxdb/issues/3235
