### ISSUE TITLE
Sign up for our newsletter is not a link

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#15]
Appears on http://influxdb.com/contact/index.html, http://influxdb.com/blog.html, http://influxdb.com/community/index.html, and http://influxdb.com/download/index.html. The right-side nav needs to be fixed and I think that will cover all cases.

**Comment by beckettsean** [comment]
Looks like it's my AdBlock preventing it from showing. Not sure what we can do about that. The strange thing is the form on the homepage works fine with AdBlock, it's only the one on right nav that is hidden for me.

**Comment by gunnaraasen** [comment]
It looks like the form is flagged by one of AdBlock's customized filters. @beckettsean any chance you can track down which filter is blocking the form? Then we can tweak the form to be skipped by the filter or reach out to the filter maintainer.

http://support.getadblock.com/kb/other-problems/adblock-is-blocking-something-that-isnt-an-ad

**Comment by beckettsean** [comment]
The specific filter list is "Fanboy's Annoyances (removes annoyances on the Web)"

http://fanboy.co.nz/ is their webpage
Report incorrect blocks on the forum: http://forums.lanik.us/viewforum.php?f=64&sid=3161d629e5ab1588cb7e053de0473fa9

Looks like a known issue, and one they won't fix: http://forums.lanik.us/viewtopic.php?f=64&t=17277&p=58173

There's a reasonable workaround in the last comment, where if the form is blocked there's a link visible to the MailChimp site.

**Comment by beckettsean** [comment]
mooted by new site.
