### ISSUE TITLE
Following the 'Reading and Writing Data' example ends up in an error

### ISSUE THREAD

**Issue by mihaicostin** [influxdb/influxdb.com#16]
`> brew install influxdb --devel`
`==> Summary`
`🍺  /usr/local/Cellar/influxdb/0.9.0-rc33: 4 files, 25M, built in 15 seconds`
`> influxd -config /usr/local/etc/influxdb.conf`
`> curl -G http://localhost:8086/query --data-urlencode "q=CREATE DATABASE mydb"`
`{"results":[{}]}`
`> curl -XPOST 'http://localhost:8086/write' -d ' { "database": "mydb", "retentionPolicy": "default", "name": "cpu_load_short", "points": [ { "name": "cpu_load_short", "tags": { "host": "server01", "region": "us-west" }, "time": "2009-11-10T23:00:00Z", "fields": { "value": '0.64' } } ] } '`
`{"error":"missing measurement"}`

install instructions taken from http://influxdb.com/docs/v0.9/introduction/installation.html
curl commands taken from http://influxdb.com/docs/v0.9/concepts/reading_and_writing_data.html
os x 10.10.3

**Comment by gunnaraasen** [comment]
Thanks @mihaicostin we'll have this updated in a few hours.

**Comment by beckettsean** [comment]
RC33 has known issues that are solved on 0.9.0 final. Currently Homebrew is still delivering RC33, but that will be fixed today, we anticipate. The PR is awaiting review.

**Comment by gunnaraasen** [comment]
The PR to update the homebrew InfluxDB formula has been merged. Homebrew/homebrew#40588.
