### ISSUE TITLE
Docs should have title linking

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb.com#162]
Previously, you could link to any H element by simply hovering over the title and clicking it. That would update the address bar to that anchor on the page, which you can then easily share. Kind of like how github does it on markdown files. We should do this.

**Comment by beckettsean** [comment]
Unfortunately, Hugo makes this tough.

Gunnar, how challenging will this be to implement? We do really need the ability to link to sections.

**Comment by toddboom** [comment]
I think there was some strange workaround for Middleman that we'd employed to make this work. It's a common enough requirement, that there must be some reasonable way to do it.

**Comment by pauldix** [comment]
yeah, the way I did it before was just through javascript. Basically, for
any docs page look for H tags and then linkify them. It was a total hack,
but worked

**Comment by toddboom** [comment]
Who could possibly have been responsible for the janky JS?

**Comment by pauldix** [comment]
all me :)

**Comment by beckettsean** [comment]
Can you point Gunnar to the relevant janky JS in the .org repo?

**Comment by gunnaraasen** [comment]
Yeah... I might just reuse the javascript snippet.

Also, Hugo adds a unique ID suffix to every header anchor (see [docs](http://gohugo.io/extras/crossreferences/)). It's not a problem for making anchors click-to-copy, but the url looks ugly, e.g. https://influxdb.com/docs/v0.9/introduction/overview.html#key-features:68f80267fa3a50980dbb745a782b8dca. I think there should be a way to disable the suffix thing site-wide, just need to figure out the config setting.

**Comment by pauldix** [comment]
here is the janky coffeescript: https://github.com/influxdb/influxdb.org/blob/master/source/layouts/docs.v0.9.index.html.slim#L94-L98

You'll want to replace those IDs with friendly names. For that just grab the innerText of the H tag, downcase it, clean it of all  non-characters and spaces, then replace the spaces with `_`.

**Comment by gunnaraasen** [comment]
Thanks!
