### ISSUE TITLE
Document SHOW SERVERS

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#170]
Cluster admin page.

**Comment by gunnaraasen** [comment]
Does `SHOW SERVERS` work right now?

**Comment by beckettsean** [comment]
it does for me in 0.9.2

```
> show servers
id	url
1	http://127.0.0.1:8088

```

**Comment by beckettsean** [comment]
tackle this as part of #171, probably

**Comment by beckettsean** [comment]
@mjdesa can you add an example of actual `SHOW SERVERS` output on the clustering page? Once that's done we can close this.
