### ISSUE TITLE
[new page] document how to save dashboards in Grafana

### ISSUE THREAD

**Issue by oliland** [influxdb/influxdb.com#172]
Our hosted InfluxDB instance comes with Grafana, but it's very unclear how to save dashboards and share them amongst our team.

**Comment by beckettsean** [comment]
We will not be adding cloud documents to the .com repo, but are working on a knowledgebase for the hosted solution.

**Comment by beckettsean** [comment]
available now in the knowledgebase at support.influxdb.com
