### ISSUE TITLE
Improve line protocol documentation

### ISSUE THREAD

**Issue by mjdesa** [influxdb/influxdb.com#173]
As noted in https://github.com/influxdb/influxdb/issues/3498

>It would be nice to improve a bit the line protocol documentation by 
 - adding = and \ to the list of chars to be escaped (maybe evident, but you never know) and 
 - re-specify the default unicode encoding used (utf8?) if applicable (or raw bytes if not).

>thanks

**Comment by beckettsean** [comment]
Re-opening as we still need to document the default encoding. I'm 99% sure it's UTF-8 but let's be 100% before documenting it.

**Comment by beckettsean** [comment]
@jwilder for the line protocol, is our default encoding UTF-8 or something else?

**Comment by jackzampolin** [comment]
https://github.com/influxdb/influxdb.com/issues/228

**Comment by jackzampolin** [comment]
Linked to: https://github.com/influxdb/influxdb/issues/4378
