### ISSUE TITLE
Schema Exploration Docs: Show Measurements and Show Series responses reversed

### ISSUE THREAD

**Issue by ameske** [influxdb/influxdb.com#176]
From the documentation wording, it looks like the example responses for "Show Measurements" and "Show Series" are reversed.

https://influxdb.com/docs/v0.9/query_language/schema_exploration.html

**Comment by beckettsean** [comment]
@ameske no, they are correct. Please review the definitions of measurement and series on https://influxdb.com/docs/v0.9/concepts/glossary.html and see if that clarifies things.

**Comment by ameske** [comment]
Oh, whoops! I completely read things incorrectly. This is what I get for
trying to skim things at the end of the day. Thanks for the quick
clarification!!​!
