### ISSUE TITLE
shine on ribbons doesn't align with the bends

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#18]
Looks off on desktop and mobile.
![screen shot 2015-06-11 at 13 52 17](https://cloud.githubusercontent.com/assets/6537329/8117983/2c0a5db6-1041-11e5-829a-caa09b06ffae.png)
![screen shot 2015-06-11 at 13 52 12](https://cloud.githubusercontent.com/assets/6537329/8117984/2c0c7df8-1041-11e5-82a2-866bbe406c70.png)

**Comment by gunnaraasen** [comment]
Must have been a typo by the designer. The ribbon shine is now aligned. :smile:

**Comment by glogic** [comment]
Thank you!! Yeah, I remember seeing that in the original design. It looks
much better.

Genevieve Douglass
http://genevievedouglass.com
347-935-5265
