### ISSUE TITLE
[minor nit] the installation instructions don't correctly copy/paste with newlines

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#181]
E.g. https://influxdb.com/download/index.html

The layout shows two lines:

![screen shot 2015-07-29 at 17 00 31](https://cloud.githubusercontent.com/assets/6537329/8972890/5afdcc64-3613-11e5-85b0-d55193177288.png)

but copy and paste results in 

```
brew update brew install influxdb
```

Presumably related to the `<code>` block they are in. Maybe we should reconsider using that?

**Comment by gunnaraasen** [comment]
I think it may actually be the syntax highlighter which strips the newlines on copy. I'll look into this.

**Comment by gunnaraasen** [comment]
Not sure what changed but it seems like new lines are now preserved in the code blocks. Tested in Chrome, Firefox, and Safari on OS X.
