### ISSUE TITLE
[new page] how to improve write performance influxdb

### ISSUE THREAD

**Issue by zengzhihai** [influxdb/influxdb.com#188]
how to improve write performance influxdb

how to improve write performance influxdb

**Comment by beckettsean** [comment]
Probably put this under the Guides section.

**Comment by beckettsean** [comment]
split /wal and /data on separate physical drives, if possible

**Comment by beckettsean** [comment]
@jackzampolin can you take https://docs.google.com/document/d/1q0Jjrs_LIOpMfPNk0hGlJu_VUH88UhF4rW5tTBZM7Os/edit and make it into a docs page? It's not finished but is a good start.

**Comment by jackzampolin** [comment]
https://github.com/influxdb/influxdb.com/pull/529

**Comment by beckettsean** [comment]
effects of Batching
Data types/shape (# fields, timestamp order)
Encryption

**Comment by beckettsean** [comment]
UDP vs. HTTP

**Comment by beckettsean** [comment]
What config settings matter?
