### ISSUE TITLE
JS error every second on Jobs page mobile view

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#19]
URL: https://boards.greenhouse.io/influxdb#.VXn1_YZVgoJ
![screen shot 2015-06-11 at 13 55 56](https://cloud.githubusercontent.com/assets/6537329/8118048/b541b976-1041-11e5-8165-0314df2e7dbb.png)

**Comment by kfitzpatrick** [comment]
That's a web worker error because of cross origin policy restrictions 

------

Kevin Fitzpatrick

@kfitzpatrick
267.254.6225

**Comment by kfitzpatrick** [comment]
What is AddThis?

------

Kevin Fitzpatrick

@kfitzpatrick
267.254.6225

**Comment by glogic** [comment]
Todd handled getting this switched over, but I think you should have access
to that stuff in Greenhouse, Kevin. (Maybe you've already looked at it, but
if not...) If you go to Greenhouse Home > Configure > Dev Center

Genevieve Douglass
http://genevievedouglass.com
347-935-5265


On Thu, Jun 11, 2015 at 2:02 PM, Kevin Fitzpatrick <notifications@github.com

**Comment by mjdesa** [comment]
Doesn't seem to be an issue anymore.
