### ISSUE TITLE
Document the epoch=true parameter

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb.com#196]
When making a query if you add this parameter, timestamps will come back as epochs. Context: https://github.com/influxdb/influxdb/issues/3549#issuecomment-127652837

**Comment by beckettsean** [comment]
It's mostly already there, just clarified it a bit. The whole page needs a rewrite but now's not the time to dig in on that. https://github.com/influxdb/influxdb.com/pull/198

**Comment by beckettsean** [comment]
closed by #198
