### ISSUE TITLE
Use actual version number in RPM filename instead of "latest"

### ISSUE THREAD

**Issue by labrown** [influxdb/influxdb.com#20]
Instructions on http://influxdb.com/download/index.html show the RPM file name `influxdb-latest-1.x86_64.rpm` which doesn't work with Ansible at all.  My playbook skips right over installing that RPM.

I could not find an `influxdb-0.9.0-1.x86_64.rpm` on your S3.  Can you please make it available so those of us using change management processes can take advantage?

**Comment by gunnaraasen** [comment]
@labrown We'll post a rpm with v0.9.0 in the filename soon.

**Comment by gunnaraasen** [comment]
Versioned RPM (and deb) download links are now on the [0.9 installation page](http://influxdb.com/docs/v0.9/introduction/installation.html).
