### ISSUE TITLE
Reserved keywords used in tags cause problems with queries

### ISSUE THREAD

**Issue by matthewmcneely** [influxdb/influxdb.com#202]
I'd suggest that you make it clear that using reserved keywords in tags causes issues. For instance I was trying to use tag labelled "Group". This was the error I was getting querying the database:

```
> show series
name: unittest
--------------
_key											entity		group	id	location	workcenter
unittest,entity=seeedstudio.com,group=test,id=test,location=test,workcenter=test	nimbleindustry.com	test	test	test		test

> select * from unittest
ERR: found GROUP, expected identifier, string, number, bool at line 1, char 64
```

**Comment by beckettsean** [comment]
References on syntax page: https://influxdb.com/docs/v0.9/write_protocols/write_syntax.html and troubleshooting page: https://influxdb.com/docs/v0.9/guides/troubleshooting.html recommending against keywords as identifiers.

This specific error is not intended behavior, there are a few related issues open, https://github.com/influxdb/influxdb/issues/3467 being the one I found first.
