### ISSUE TITLE
Line protocol messages can crash the service

### ISSUE THREAD

**Issue by shawjef3** [influxdb/influxdb.com#204]
I have a random line protocol message generator that to the best of my knowledge creates messages that conform to the specification. Influxdb doesn't parse all the messages, which is a bug in my generator or in Influxdb.

What certainly is a bug in Influxdb is that some messages cause the service to crash. Following are links to the console output of the service, and a zip of the messages, one message per file. I sent each message to Influxdb in its own UDP packet. The message files are UTF-8 encoded, and were sent to Influxdb UTF-8 encoded.

http://www.jeffshaw.me/influxdb/log.txt
http://www.jeffshaw.me/influxdb/messages.zip

Line 36 is where the crash begins.

```panic: runtime error: slice bounds out of range```

**Comment by mjdesa** [comment]
@shawjef3 this is an influxdb issue. Can you open an issue for this there?

**Comment by jwilder** [comment]
@shawjef3 That error might have been fixed yesterday via https://github.com/influxdb/influxdb/pull/3570
