### ISSUE TITLE
document how to uninstall/remove InfluxDB

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#207]
Inspired by https://github.com/influxdb/influxdb/issues/1316

**Comment by beckettsean** [comment]
fixed by new repos site, so users can use `apt-get uninstall` or `yum uninstall`

**Comment by danielwertheim** [comment]
Is `apt-get uninstall influxdb` really the correct command? Shouldn't it be `apt-get remove influxdb`? For me the first fails the second succeeds.

And where's this in the docs as this one is closed as part of `v0.9.5`?

**Comment by beckettsean** [comment]
closing in favor of https://github.com/influxdb/docs.influxdata.com/issues/95
