### ISSUE TITLE
In the documentation, all of the section headings say "undefined"

### ISSUE THREAD

**Issue by ianflint** [influxdb/influxdb.com#214]

**Comment by ianflint** [comment]
I noticed this in the download and quick start pages.

**Comment by gunnaraasen** [comment]
Thanks for the report @ianflint. They're showing up correctly for me.

It could be a caching issue. I've reset all pages on our CDN. Are you still seeing "undefined" headers?

**Comment by gunnaraasen** [comment]
Turned out to be a cross-browser issue with the javascript snippet we're using to create section header links. The fix will be up in the next 15 min.

**Comment by ianflint** [comment]
Thanks for the quick reply.
- Ian
 


     On Tuesday, August 11, 2015 11:11 AM, Gunnar <notifications@github.com> wrote:
   

 Turned out to be a cross-browser issue with the javascript snippet we're using to create section header links. The fix will be up in the next 15 min.—

**Comment by gunnaraasen** [comment]
This should be fixed now.
