### ISSUE TITLE
Confusing wording on retention policies

### ISSUE THREAD

**Issue by ianflint** [influxdb/influxdb.com#215]
I noticed this on the page https://influxdb.com/docs/v0.9/administration/administration.html

To delete a retention policy issue the following command:

SHOW RETENTION POLICIES ON <database>

On a related note, how do you delete a retention policy?

**Comment by beckettsean** [comment]
@ianflint thanks for the report. I've updated the docs and the command is `DROP RETENTION POLICY <rp> ON <db>`
