### ISSUE TITLE
Data is written as update when previously written as create in v0.8

### ISSUE THREAD

**Issue by eliperelman** [influxdb/influxdb.com#220]
When writing data with shared timestamps, it seems that each write does an update instead of a create. I'm not sure if this is a change from v0.8 to v0.9.2 which I am using because I couldn't find anything in the release notes about this. I've created a reduced test case:

1. Write the following 5 lines:

```
measure,metric=test value=100.0 1439418072324
measure,metric=test value=200.0 1439418072324
measure,metric=test value=300.0 1439418072324
measure,metric=test value=400.0 1439418072324
measure,metric=test value=500.0 1439418072324
```

2. Query for values:

```
select * from measure where metric = 'test'
```

3. Note only 1 record, the last one to be written.

![query](https://cldup.com/mxvK7vznp3-3000x3000.png)

If this is a change of behavior, could someone point me to the documentation surrounding it? If this is expected, could someone then point me to how to set this back to doing creates?

**Comment by otoolep** [comment]
This is by design. A point destined for a given database and retention policy, with exactly the same timestamp as one already in database, overwrites the existing point.

There is currently no support for "creates" in the 0.9 release, though we have discussed possible ways to do it.

**Comment by eliperelman** [comment]
@otoolep is this a change from v0.8? From what I understand, in order to do updates with previous versions, you had to have the sequence number as well, but I don't see anything like that in v0.9.x.

**Comment by otoolep** [comment]
Yes, this is a difference between 0.8 and 0.9. There are no sequence numbers in 0.9.

**Comment by gunnaraasen** [comment]
@eliperelman we'll be adding a section listing out all the differences between 0.8 and 0.9 as part of the 0.8 to 0.9 migration docs.
