### ISSUE TITLE
InfluxDB crashed under load

### ISSUE THREAD

**Issue by ianflint** [influxdb/influxdb.com#222]
I was doing a bulk load into influxDB at Yahoo, and it crashed.

Here are the specifics:
Running on an openstack VM with
  two CPU allocated,
  4GB RAM,
  107GB Virtual Disk,
  RHEL 6.6 (64 Bit) - 2.6.32-431.23.3

I notice a few bad behaviors:

First, the server would return 500 responses until it flushed points, and then it would go back to 204 responses.  Here's an example:
[http] 2015/08/13 10:37:51 ::1 - - [13/Aug/2015:10:37:50 +0000] POST /write?db=net_test HTTP/1.1 204 0 - - 5852fa0c-41a7-11e5-b49e-000000000000 1.095539723s
[http] 2015/08/13 10:37:51 ::1 - - [13/Aug/2015:10:37:51 +0000] POST /write?db=net_test HTTP/1.1 204 0 - - 58ff03d8-41a7-11e5-b49f-000000000000 108.762595ms
[http] 2015/08/13 10:37:51 ::1 - - [13/Aug/2015:10:37:51 +0000] POST /write?db=net_test HTTP/1.1 204 0 - - 5914ac73-41a7-11e5-b4a0-000000000000 137.166907ms
[http] 2015/08/13 10:37:51 ::1 - - [13/Aug/2015:10:37:51 +0000] POST /write?db=net_test HTTP/1.1 204 0 - - 592ea571-41a7-11e5-b4a1-000000000000 145.381486ms
[http] 2015/08/13 10:37:51 ::1 - - [13/Aug/2015:10:37:51 +0000] POST /write?db=net_test HTTP/1.1 204 0 - - 5949ad8a-41a7-11e5-b4a2-000000000000 191.109206ms
[http] 2015/08/13 10:37:52 ::1 - - [13/Aug/2015:10:37:52 +0000] POST /write?db=net_test HTTP/1.1 204 0 - - 596ebc38-41a7-11e5-b4a3-000000000000 139.672744ms
[http] 2015/08/13 10:37:57 ::1 - - [13/Aug/2015:10:37:52 +0000] POST /write?db=net_test HTTP/1.1 500 8 - - 5989f415-41a7-11e5-b4a4-000000000000 5.004170123s
[http] 2015/08/13 10:38:02 ::1 - - [13/Aug/2015:10:37:57 +0000] POST /write?db=net_test HTTP/1.1 500 8 - - 5c8d211f-41a7-11e5-b4a5-000000000000 5.277618526s
[http] 2015/08/13 10:38:07 ::1 - - [13/Aug/2015:10:38:02 +0000] POST /write?db=net_test HTTP/1.1 500 8 - - 5fd4adc4-41a7-11e5-b4a6-000000000000 5.203838367s
[http] 2015/08/13 10:38:13 ::1 - - [13/Aug/2015:10:38:08 +0000] POST /write?db=net_test HTTP/1.1 500 8 - - 63030dc4-41a7-11e5-b4a7-000000000000 5.168254414s
[http] 2015/08/13 10:38:18 ::1 - - [13/Aug/2015:10:38:13 +0000] POST /write?db=net_test HTTP/1.1 500 8 - - 66290c96-41a7-11e5-b4a8-000000000000 5.026161599s
[http] 2015/08/13 10:38:23 ::1 - - [13/Aug/2015:10:38:18 +0000] POST /write?db=net_test HTTP/1.1 500 8 - - 69305036-41a7-11e5-b4a9-000000000000 5.04217651s
[shard] 2015/08/13 10:38:25 flush 88700 points in 33.253s
[http] 2015/08/13 10:38:26 ::1 - - [13/Aug/2015:10:38:23 +0000] POST /write?db=net_test HTTP/1.1 204 0 - - 6c39e2e6-41a7-11e5-b4aa-000000000000 2.666516615s
[http] 2015/08/13 10:38:26 ::1 - - [13/Aug/2015:10:38:26 +0000] POST /write?db=net_test HTTP/1.1 204 0 - - 6dd758d9-41a7-11e5-b4ab-000000000000 682.503952ms
[http] 2015/08/13 10:38:27 ::1 - - [13/Aug/2015:10:38:27 +0000] POST /write?db=net_test HTTP/1.1 204 0 - - 6e44efc0-41a7-11e5-b4ac-000000000000 87.540081ms
[http] 2015/08/13 10:38:27 ::1 - - [13/Aug/2015:10:38:27 +0000] POST /write?db=net_test HTTP/1.1 204 0 - - 6e5ab120-41a7-11e5-b4ad-000000000000 125.655127ms
[http] 2015/08/13 10:38:27 ::1 - - [13/Aug/2015:10:38:27 +0000] POST /write?db=net_test HTTP/1.1 204 0 - - 6e75935d-41a7-11e5-b4ae-000000000000 101.985689ms

Second, at some point the server mysteriously died.

I've ruled out the disk being full - it still has plenty of space, and the size of the database is currently 4.9 GB.  

I was feeding it approximately 100M datapoints just as fast as it could consume them.  I was feeding them via the HTTP interface, in batches of 1000-1100 datapoints per post.

The test started at 7:08 GMT and ended at 10:39 GMT, and in that time there were 56898 posts, of which 56607 were successful, 40 returned status code 400, and 251 returned status code 500.  It's also interesting to note that the first status code 500 occurred at 08:24 GMT, over an hour into the test.  If it helps, here's the list of times for 500 responses.  They definitely seemed to be more frequent further into the test.

08:24:02
08:29:41
08:30:06
08:42:06
08:57:42
08:57:49
09:00:03
09:04:06
09:07:33
09:08:04
09:14:03
09:14:09
09:17:07
09:21:02
09:21:15
09:28:22
09:35:06
09:38:38
09:38:46
09:39:13
09:39:27
09:42:15
09:42:44
09:42:51
09:46:03
09:46:08
09:46:20
09:46:33
09:46:40
09:46:48
09:50:33
09:50:38
09:50:46
09:50:51
09:50:58
09:51:08
09:51:13
09:51:22
09:51:31
09:51:36
09:51:45
09:51:50
09:51:57
09:54:48
09:54:56
09:55:03
09:55:08
09:55:18
09:55:28
09:55:33
09:55:40
09:55:45
09:55:54
09:56:03
09:59:40
09:59:45
09:59:55
10:00:00
10:00:05
10:00:10
10:00:19
10:00:24
10:00:34
10:00:39
10:00:45
10:00:52
10:01:03
10:01:08
10:01:13
10:01:21
10:01:32
10:01:37
10:04:22
10:04:27
10:04:35
10:04:40
10:04:47
10:04:58
10:05:03
10:05:13
10:05:23
10:05:35
10:05:40
10:05:46
10:05:51
10:09:29
10:09:34
10:09:39
10:09:49
10:09:54
10:10:03
10:10:08
10:10:13
10:10:18
10:10:24
10:10:29
10:10:34
10:10:41
10:10:47
10:10:56
10:11:01
10:11:06
10:11:11
10:11:20
10:11:31
10:11:36
10:14:38
10:14:43
10:14:53
10:14:58
10:15:06
10:15:11
10:15:16
10:15:25
10:15:30
10:15:40
10:15:45
10:15:51
10:15:57
10:16:03
10:16:10
10:16:15
10:16:23
10:19:54
10:19:59
10:20:04
10:20:10
10:20:15
10:20:20
10:20:25
10:20:33
10:20:38
10:20:43
10:20:48
10:20:53
10:20:58
10:21:05
10:21:10
10:21:15
10:21:20
10:21:25
10:21:31
10:21:36
10:21:44
10:21:49
10:21:54
10:21:59
10:22:04
10:22:10
10:22:20
10:22:26
10:22:31
10:22:36
10:22:41
10:22:46
10:22:51
10:22:56
10:23:02
10:23:07
10:23:12
10:23:18
10:23:23
10:23:28
10:23:34
10:23:39
10:23:44
10:23:53
10:23:58
10:27:27
10:27:32
10:27:37
10:27:43
10:27:48
10:27:53
10:28:01
10:28:07
10:28:12
10:28:17
10:28:22
10:28:32
10:28:37
10:28:42
10:28:47
10:28:52
10:29:03
10:29:08
10:29:13
10:29:18
10:29:23
10:29:34
10:29:39
10:29:44
10:29:49
10:29:54
10:30:04
10:30:09
10:30:15
10:30:20
10:30:25
10:30:35
10:30:40
10:30:45
10:30:50
10:30:56
10:31:05
10:31:11
10:31:16
10:31:21
10:34:23
10:34:28
10:34:33
10:34:38
10:34:44
10:34:54
10:34:59
10:35:04
10:35:10
10:35:15
10:35:20
10:35:25
10:35:34
10:35:39
10:35:45
10:35:50
10:35:55
10:36:04
10:36:09
10:36:15
10:36:20
10:36:25
10:36:31
10:36:38
10:36:43
10:36:48
10:36:53
10:37:00
10:37:05
10:37:11
10:37:16
10:37:21
10:37:29
10:37:34
10:37:39
10:37:44
10:37:49
10:37:57
10:38:02
10:38:07
10:38:13
10:38:18
10:38:23

Please let me know if there's any other information you need to help troubleshoot this.  I'll leave everything as it was the moment it crashed in case you need me to do any diagnostics.

**Comment by beckettsean** [comment]
This is the documentation repo, not the code repo. Please open bug reports for InfluxDB on https://github.com/influxdb/influxdb/issues/new. 

That said, these issues are known problems in 0.9.2 (search the issues for `500`) that have been fixed in 0.9.3, soon to be released (or you can grab a [nightly build](https://influxdb.com/download/index.html))
