### ISSUE TITLE
[new page] assumptions and tradeoffs in InfluxDB

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#226]
High write volumes
High read volumes
Infrequent deletes, most deletes are bulk removal
Nulls are not stored
No user-defined indexes

**Comment by jackzampolin** [comment]
@beckettsean [this page](https://influxdb.com/blog/2015/06/03/InfluxDB_clustering_design.html) on the blog touches on these issues.  Going to condense it down and put it either in a new page in the Concepts section or add it to the Key Concepts page?  Thoughts?

**Comment by beckettsean** [comment]
Concepts section, new page. Condensing it is good, and link to the post for those who want more detail.
