### ISSUE TITLE
No units for query timestamp means nanoseconds

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb.com#229]
https://influxdb.com/docs/v0.9/guides/querying_data.html

Timestamp Format - if just an integer is supplied for a timestamp, and no units are supplied, the number is interpreted as nanoseconds.

@DanielMorsing

**Comment by beckettsean** [comment]
@rkuchan can you make sure that #252 includes this info?

**Comment by jackzampolin** [comment]
Was solved by https://github.com/influxdb/influxdb.com/pull/252
