### ISSUE TITLE
Missing link on Getting Started page

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#23]
http://influxdb.com/docs/v0.9/introduction/getting_started.html

"The CLI communicates with InfluxDB by making requests to the InfluxDB API. All clients currently interact with InfluxDB through the API except for `[services]()`, which are directly integrate with the database."

There are a number of grammatical errors there, too. I'll try to fix those in a PR.

**Comment by gunnaraasen** [comment]
Fixed by #24
