### ISSUE TITLE
influxdb.com Documentation Display Issue

### ISSUE THREAD

**Issue by s1m0** [influxdb/influxdb.com#242]
Documentation content is displayed below the left side menu bar instead of starting alongside it.

Tested with Chrome, FireFox & IE 11

**Comment by otoolep** [comment]
@s1m0 -- can you provide a screenshot demonstrating the issue?

**Comment by beckettsean** [comment]
@s1m0 we will need more info to track this down, since I cannot reproduce it at all in any browser on OS X.

What version of Windows are you running? Please provide screenshots from Chrome.

**Comment by beckettsean** [comment]
Screenshot of IE 11 from @s1m0:

![image](https://cloud.githubusercontent.com/assets/6537329/9419651/5a3aa926-4812-11e5-84da-f9f98e5571f6.png)

**Comment by dgnorton** [comment]
I can't reproduce on Win8.1 with Chrome 44 or IE11.

**Comment by gunnaraasen** [comment]
@s1m0 Do you have Javascript disabled?
