### ISSUE TITLE
JSON Protocol Page Needs Withdrawl Schedule

### ISSUE THREAD

**Issue by s1m0** [influxdb/influxdb.com#243]
Please update the JSON Protocol documentation with details of when it will be withdrawn. I, for one, have a lot of work to do before that date to convert to the line protocol.

**Comment by beckettsean** [comment]
@pauldix do we have a firm deadline for the end of the JSON write protocol?

**Comment by pauldix** [comment]
Let's just hold it off until 1.0. No reason to remove it before then. But we shouldn't have the JSON protocol up on docs anymore. The only thing it should say is, "this is deprecated and will be removed in the 1.0 release. If you have questions about it, you'd be better off implementing the line protocol <link>"

**Comment by s1m0** [comment]
I happen to like the JSON protocol ;-)
