### ISSUE TITLE
user 

### ISSUE THREAD

**Issue by panqingcui** [influxdb/influxdb.com#249]
Unused users can still create a database ?
![image](https://cloud.githubusercontent.com/assets/10126345/9437280/0544af48-4a88-11e5-8a83-94ad3563dce7.png)

**Comment by gunnaraasen** [comment]
@panqingcui Authentication and authorization need to be enabled in the config file by setting the `auth-enabled` option to true. See the [authentication](https://influxdb.com/docs/v0.9/administration/authentication.html) and [authorization](https://influxdb.com/docs/v0.9/administration/authorization.html) docs.
