### ISSUE TITLE
Clarify cluster node roles (Raft vs. Data)

### ISSUE THREAD

**Issue by cschneid** [influxdb/influxdb.com#250]
As per discussion: https://groups.google.com/d/msg/influxdb/hn8RVqaUD0Q/h-iUcWj5BAAJ

It'd be nice to have some documentation around the roles different nodes have, the limitations in 0.9.3 (which seem to be lessening in future versions), and operational guides on how to deal with nodes going down of each type.

**Comment by beckettsean** [comment]
@mjdesa can you incorporate some additional data in the clustering doc?

**Comment by mjdesa** [comment]
on it
