### ISSUE TITLE
field key in glossary is confusing

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#258]
We mention how to write integers, but not strings (must double-quote). I don't think we should mention syntax in the glossary unless absolutely necessary, that's better covered in the "Data Types" section in https://influxdb.com/docs/v0.9/write_protocols/write_syntax.html#line-protocol

**Comment by mjdesa** [comment]
@beckettsean so if I understand correctly, you would like me to remove anything syntax related from the glossary to the `write_syntax`?

**Comment by beckettsean** [comment]
Pretty much. Mostly it's weird that we mention `i` for ints, but not `"` for strings, for instance. Overall, though, as a glossary, it should describe the meanings, not the syntax for use.

**Comment by mjdesa** [comment]
sounds good

**Comment by mjdesa** [comment]
closed by https://github.com/influxdb/influxdb.com/pull/264
