### ISSUE TITLE
Influx Db using system time rather than the time given in the data.

### ISSUE THREAD

**Issue by PriyankaBadam** [influxdb/influxdb.com#260]
Hi,

I am not able to insert data with respect to time stamp,Any format i gave in the time field , i am seeing the data is being inserted with systems timestamp.Following is the sample data, pls help.
i tried the unix time stamp even, like 1440072000000 but ts taking the same system timestamp

{
    "database": "mydb1",
    "retentionPolicy": "default",
    "points": [
        {
            "name": "dbdashboard",
            "tags": {
                "service": "customerservice",
"Fault":"true"
            },
      "time": "2015-07-16T14:34:57.532-07:00"
            "fields": {
                "value": 203
            }
        }
    ]
}

**Comment by otoolep** [comment]
The JSON API is deprecated. It highly recommended you move to the line protocol which is the only input method support.

https://influxdb.com/docs/v0.9/guides/writing_data.html#writing-data-using-the-http-api
https://influxdb.com/docs/v0.9/write_protocols/line.html

If you have any issues with using the line protocol, the mailing list is a good place to ask questions, or open another ticket if you encounter a potential bug.
