### ISSUE TITLE
downloads page is wrong about telegraf 0.1.6 and homebrew

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#266]
see https://github.com/influxdb/telegraf/issues/146. Maybe we should remove the homebrew install from downloads for now?

**Comment by sparrc** [comment]
I'm a little lost, where does it say that the telegraf homebrew is 0.1.6? Is it somewhere on the docs page?

**Comment by beckettsean** [comment]
@sparrc it's on the downloads page: https://influxdb.com/download/index.html https://github.com/influxdb/influxdb.com/blob/master/content/site/download.md.

We need some advance notice of telegraf releases so we can update the downloads page appropriately.

**Comment by sparrc** [comment]
@beckettsean sorry I didn't realize before that this existed, good to know! I'll make sure to keep this page updated going forward
