### ISSUE TITLE
Add tarball link to Downloads page

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb.com#267]
Each numbered build e.g. 0.9.3, is available in tarball form for those who do not wish to deal with packages. For example, for 0.9.3 the following is available:

https://s3.amazonaws.com/influxdb/influxdb_0.9.3_x86_64.tar.gz 

We should list this on the Downloads page.

**Comment by otoolep** [comment]
E.g.

TAR

    64-bit system download and decompress instructions

    wget https://s3.amazonaws.com/influxdb/influxdb_0.9.3_x86_64.tar.gz
    tar xvfz influxdb_0.9.3_x86_64.tar.gz

**Comment by beckettsean** [comment]
I had this as the final step in #76, but this is a cleaner issue so closed that in favor of this.

**Comment by beckettsean** [comment]
Do this for telegraf, too.

**Comment by gunnaraasen** [comment]
Fixed in #353
