### ISSUE TITLE
Outdated note regarding clustering state on the config page

### ISSUE THREAD

**Issue by mmalecki** [influxdb/influxdb.com#270]
https://influxdb.com/docs/v0.9/administration/config.html#cluster:

> Note: Clustering is in alpha state right now and all clusters must contain three and only three nodes.

Where as release notes for 0.9.3 mention that a cluster of exactly 3 is no longer required.

**Comment by beckettsean** [comment]
Good catch, @mmalecki. With the new https://influxdb.com/docs/v0.9/guides/clustering.html page I think we can just remove that whole section. The page is due for an overhaul in the 0.9.4 cycle, anyway.
