### ISSUE TITLE
document shard group durations

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#275]
If the RP has a duration less than 2 days, all shards are 1h shards. If the RP has a duration of 2 days to 6 months, all shards are 1d shards. For durations greater than 6 months, all shards are 7d shards.

If writes are slowing down as the BoltDB files grow, moving to a narrower shard duration should help.

**Comment by beckettsean** [comment]
@otoolep will this still apply in the `tsm` world?

**Comment by otoolep** [comment]
Yes, nothing about shard group duration is changed by engine type.

**Comment by otoolep** [comment]
Oh, and since Bolt is not part of tsm, any concerns about that are moot. I don't believe write-throughput should be affected as file size increase.

cc @jwilder
