### ISSUE TITLE
Installation docs out of date with download docs

### ISSUE THREAD

**Issue by sparrc** [influxdb/influxdb.com#277]
This page is still pointing to 0.9.2
https://github.com/influxdb/influxdb.com/blob/master/content/docs/v0.9/introduction/installation.md

while the downloads page points to 0.9.3
https://github.com/influxdb/influxdb.com/blob/master/content/site/download.md

Maybe the "download" page should point to the installation page, or vice-versa, so that this only needs to be maintained in one place

I can at least put up a PR to fix the installation page shortly

**Comment by beckettsean** [comment]
closed by #278

**Comment by beckettsean** [comment]
https://github.com/influxdb/influxdb.com/issues/279 for the longer term solution
