### ISSUE TITLE
[new page] list of licenses and dependency licenses for contracts

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#281]
We need a single URL that we can put into the contracts that points to all relevant licenses.

E.g.

```
Telegraf License - https://github.com/influxdb/telegraf/blob/master/LICENSE
InfluxDB License - https://github.com/influxdb/influxdb/blob/master/LICENSE
Chronograf License - https://github.com/influxdb/chronograf/blob/master/LICENSE
Kapacitor License - https://github.com/influxdb/kapacitor/blob/master/LICENSE

Telegraf Dependencies - https://github.com/telegraf/influxdb/blob/master/LICENSE_OF_DEPENDENCIES.md
InfluxDB Dependencies - https://github.com/influxdb/influxdb/blob/master/LICENSE_OF_DEPENDENCIES.md
Chronograf Dependencies - https://github.com/chronograf/influxdb/blob/master/LICENSE_OF_DEPENDENCIES.md
Kapacitor Dependencies - https://github.com/kapacitor/influxdb/blob/master/LICENSE_OF_DEPENDENCIES.md
```

**Comment by gunnaraasen** [comment]
Is there a strong reason for keeping a separate license file for dependencies?

Could all third party licenses be listed at the end of the existing LICENSE file? Presumably anyone interested in InfluxDB's license will already be looking at the LICENSE file and may not realize there is a separate file with third party licenses.

**Comment by beckettsean** [comment]
I think there's an assumption that a LICENSE file in the root of the repo contains only the license for that repo. Automated scripts check for it and process it. If we expand it, I worry that it will obscure our actual license.

Mongo, Cassandra, OpenTSDB, and Git all have a standalone file in the root of the repo with the license in it. They all document dependency licensing in different ways.

**Comment by beckettsean** [comment]
https://github.com/influxdb/influxdb/blob/master/LICENSE_OF_DEPENDENCIES.md
