### ISSUE TITLE
Changes links on installation page to always be latest version

### ISSUE THREAD

**Issue by brewneaux** [influxdb/influxdb.com#294]
Currently, the download links for the rpm and deb packages are going to 0.9.2.

**Comment by otoolep** [comment]
The links looks fine to me here:

https://influxdb.com/download/index.html

**Comment by brewneaux** [comment]
Ah, I was referring to this page: https://influxdb.com/docs/v0.9/introduction/installation.html

**Comment by beckettsean** [comment]
It's fixed in the latest code (https://github.com/influxdb/influxdb.com/commit/f1cd33059defeaba691b5b357b868fb1dd0f4f02), just hasn't been pushed yet.
