### ISSUE TITLE
Add prominent docs in the API intro disabusing people of the notion of "HTTP" and "REST"

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb.com#306]
For some reason a number of people really get hung up on the idea that HTTP is simply a transport for the InfluxDB API and that its semantics are not used in any way. We should clearly document this.

The reasoning for using HTTP was simple: there are easy to use libraries in every language to make HTTP requests, making it an ideal candidate for sending InfluxQL requests to the database. However, it is only a transport.

See https://twitter.com/Kozure1024/status/642360310142099457 for example of the confusion.

**Comment by beckettsean** [comment]
Good idea, @pauldix, and reminds me to explain that InfluxQL [isn't CRUD](https://github.com/influxdb/influxdb.com/issues/307), either.

**Comment by beckettsean** [comment]
Put this on the Writing Data guide just before the HTTP Response Codes section.

**Comment by jackzampolin** [comment]
https://github.com/influxdb/influxdb.com/pull/358
