### ISSUE TITLE
explain that InfluxDB is not CRUD, just CRd

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#307]
Create
Read
Update
Delete

InfluxDB only does two of those fully, and has partial support for DELETE. Let's add a section to the SQL comparison page that differentiates InfluxQL from SQL in this way. Basically UPDATE doesn't exist but there is overwrite. DELETE is only for big chunks of data, at least an entire series. Link to the open issue to have DELETE SERIES support a WHERE time clause.

**Comment by jackzampolin** [comment]
https://github.com/influxdb/influxdb.com/pull/358
