### ISSUE TITLE
Link to stats and diags README

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb.com#314]
The initial README for stats and diags support is here: https://github.com/influxdb/influxdb/blob/master/monitor/README.md

This should be linked to from the Docs page of our site. I suggest a new page titled something like "Monitoring and troubleshooting" which simply links to this new README.

**Comment by otoolep** [comment]
cc @beckettsean

**Comment by beckettsean** [comment]
Regan, let's add a new page under the Troubleshooting section that links to this README for now. Call it something like "Inspecting the System". Ultimately we will document SHOW STATS, SHOW DIAGNOSTICS, SHOW SERVERS, Jason's `inspect` tool, some basic log analysis, and how to run the performance tool.
