### ISSUE TITLE
Error in Measurement section of Glossary

### ISSUE THREAD

**Issue by geoand** [influxdb/influxdb.com#323]
In the [glossary](https://influxdb.com/docs/v0.9/concepts/glossary.html) page, the documentation states:

The measurement is what appears in the **SELECT** clause of query statements, and is thus similar to a table name in traditional SQL databases.

I believe the documentation should read:

The measurement is what appears in the **FROM** clause of query statements, and is thus similar to a table name in traditional SQL databases.

**Comment by beckettsean** [comment]
Entirely true, and the glossary page is due for an overhaul, thanks for the reminder!

**Comment by geoand** [comment]
You're welcome!

**Comment by beckettsean** [comment]
Glossary reworked in #422

**Comment by geoand** [comment]
Looks great!
