### ISSUE TITLE
add duplicate point stuff to frequent issues page

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#324]
Mention that same measurement, tag set, and timestamp means same point, and the last one wins.

**Comment by esecules** [comment]
Did it used to be the case that a point was also determined by a sequence number?

**Comment by beckettsean** [comment]
Yes, that was true in 0.8. It was not kept for 0.9.

This needs to be added to the 0.8 changes page, too. There's no mention on sequence number on that page yet.
