### ISSUE TITLE
support plans page is wrong

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#331]
https://influxdb.com/support/index.html needs to be updated (lives in layouts/site/support.html)

Developer Response time is 12 hours, not six. 
Business Hours are 8 a.m. to 8 p.m. Eastern Time.
Platinum should be 1 hour response for critical issues
Gold should have 24/7 Coverage

**Comment by jackzampolin** [comment]
https://github.com/influxdb/influxdb.com/pull/345
