### ISSUE TITLE
Writing into the "future" is an issue

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb.com#332]
Something for https://influxdb.com/docs/v0.9/troubleshooting/frequently_encountered_issues.html

"I wrote data into the future, but can't seem to query it? What is wrong?"

I know it's discussed https://influxdb.com/docs/v0.9/troubleshooting/frequently_encountered_issues.html#querying-after-now, but it might help to be clearer.

**Comment by beckettsean** [comment]
would prefer to have https://github.com/influxdb/influxdb/issues/4461
