### ISSUE TITLE
This Page has broken link

### ISSUE THREAD

**Issue by harukaeru** [influxdb/influxdb.com#338]
In https://influxdb.com/docs/v0.9/write_protocols/json.html

```
line protocol
# -> https://influxdb.com/docs/v0.9/write_protocols/docs/v0.9/write_protocols/line.html
```
at the following sentence
```
The line protocol is the primary write protocol for InfluxDB 0.9.1+
```
I assume the correct link url is https://influxdb.com/docs/v0.9/write_protocols/line.html

**Comment by jackzampolin** [comment]
Thank you for the heads up!  Fixed by https://github.com/influxdb/influxdb.com/pull/340
