### ISSUE TITLE
InfluxQL cheat sheet

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#359]
List all queries with their full syntax, in alphabetical order.

**Comment by corylanou** [comment]
:100:

**Comment by beckettsean** [comment]
https://github.com/influxdb/influxdb/blob/master/influxql/INFLUXQL.md has the list of all queries and a lot of the syntax, but it needs to be simplified and we need to make some of the syntax more explicit, e.g. what can accept regex operators and what cannot.

**Comment by DreadPirateShawn** [comment]
For posterity, if you find this ticket as the first result of "influxdb cheat sheet", the docs in question now live hereabouts: https://docs.influxdata.com/influxdb/

**Comment by beckettsean** [comment]
Heh, thanks @DreadPirateShawn!
