### ISSUE TITLE
title 'structured' is spelled wrong

### ISSUE THREAD

**Issue by jeangougou** [influxdb/influxdb.com#366]
'Time Strucutred Merge Tree' should read 'Time Structured Merge Tree' at the end of the page title
at https://influxdb.com/docs/v0.9/concepts/storage_engine.html

**Comment by beckettsean** [comment]
will be fixed by https://github.com/influxdb/influxdb.com/pull/368

**Comment by beckettsean** [comment]
fixed by #374
