### ISSUE TITLE
ALTER RETENTION doesn't affect existing shards

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb.com#370]
We could do with an entry in the FAQ about this, it confuses many people. See https://github.com/influxdb/influxdb/issues/4354#issuecomment-146423179 for an example.

**Comment by beckettsean** [comment]
Regan, let's get this in for 0.9.5. I can give you the overview, it's pretty quick.

**Comment by rkuchan** [comment]
Closed in favor of https://github.com/influxdb/docs.influxdata.com/issues/48
