### ISSUE TITLE
Link to TSM installation

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb.com#371]
I see nowhere on the main website to get to this page:

https://influxdb.com/docs/v0.9/introduction/tsm_installation.html

It seems one must just "know" the link, correct?

**Comment by beckettsean** [comment]
This is intentional, Philip. Paul's blog post is the only way to find that link, preventing newbies without context from trying it.

**Comment by otoolep** [comment]
Got it, thanks.
