### ISSUE TITLE
InfluxDB may ignore huge Collectd packets

### ISSUE THREAD

**Issue by ymettier** [influxdb/influxdb.com#381]
Hello,

Could you read issue https://github.com/influxdb/influxdb/issues/1231 ?
It seems that InfluxDB-0.9 will not crash any more (issue solved).
However it will ignore big UDP packets or at least part of them.
This is what I explain in https://github.com/influxdb/influxdb/issues/1231#issuecomment-140983899

If you choose to document it, the idea is to say that standard UDP packets (Collectd configuration `MaxPacketSize 1452`) is accepted. But other (bigger ?) values will lead to data loss. You should not set `MaxPacketSize` to a bigger value.

As @beckettsean says in his last comment, maybe you should document it in https://influxdb.com/docs/v0.9/write_protocols/collectd.html ?

Note : I stopped playing with collectd binary protocol and I now prefer opentsdb and influxdb protocols because of tags. So I will not be able to test any improvement. However, the issue describes how to do it so you can easily test it.

Regards,
Yves

**Comment by otoolep** [comment]
Fixed by https://github.com/influxdb/influxdb/commit/657aa5a1348ebde47446de0fb4c43ac102602185
