### ISSUE TITLE
Renaming database now supported

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb.com#384]
This new command needs to be documented.

https://github.com/influxdb/influxdb/pull/4291

**Comment by beckettsean** [comment]
@rkuchan there's a new command for schema administration:

`ALTER DATABASE <db> RENAME TO <new_db>`

**Comment by thom-nic** [comment]
Sorry for commenting on an old, closed issue, but what was the outcome of this?  It was tagged with 0.9.5 release and closed with no PR.  I can't find any documentation on it if I search docs.influxdata and if I attempt on v0.11 I get an error:
```
Connected to http://localhost:8086 version 0.11.0
InfluxDB shell 0.12.1
> alter database foo_dev rename to foo_development
ERR: error parsing query: found DATABASE, expected RETENTION at line 1, char 7
Warning: It is possible this error is due to not setting a database.
Please set a database with the command "use <database>".
> use foo_dev
Using database foo_dev
> alter database foo_dev rename to foo_development
ERR: error parsing query: found DATABASE, expected RETENTION at line 1, char 7
```

**Comment by beckettsean** [comment]
@thom-nic the feature was not implemented.

**Comment by beckettsean** [comment]
Also, please note this is the old docs repo. The new docs repo is influxdata/docs.influxdata.com.

**Comment by thom-nic** [comment]
Ah, ok.  This issue reads as if it was implemented but not documented. Thanks for clarifying.

**Comment by Hackeruncle** [comment]
> ALTER DATABASE online_log_analysis RENAME TO loganalysis;
ERR: error parsing query: found DATABASE, expected RETENTION at line 1, char 7
>

**Comment by reshujain4u** [comment]
Same here.. seems it is not working

**Comment by jackzampolin** [comment]
This is deprecated repo with outdated information. This is not supported in InfluxDB currently.
