### ISSUE TITLE
Typo in the line protocol documentation

### ISSUE THREAD

**Issue by davazp** [influxdb/influxdb.com#387]
In the syntax reference for the line protocol:

https://influxdb.com/docs/v0.9/write_protocols/write_syntax.html

you can read:

> Measurements, tag keys, tag values, and field keys are never quoted. Spaces and commas must be
> escaped. **Field keys** that are stored as strings must always be double-quoted.

The highlighed text should be field values.

**Comment by beckettsean** [comment]
Closed by https://github.com/influxdb/influxdb.com/commit/5dc1ec8c7a08d315eb5bb1a9f9a54fcc289e05c3

**Comment by beckettsean** [comment]
Thanks, @davazp
