### ISSUE TITLE
Clustering setup documentation is wrong

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb.com#391]
This page https://influxdb.com/docs/v0.9/guides/clustering.html

The way this is documented won't actually work. The problem is that they're setting the INFLUXD_OPTS environment variable for whatever user they happen to be logged in as and then starting up the service, which uses the influxdb user, who doesn't have that variable set.

One way to fix this is to have the user set the variable like this before starting the service:

```sh
sudo su influxdb
export INFLUXD_OPTS=...
exit
# now sudo start eh service
```

**Comment by otoolep** [comment]
Where do you see that @pauldix ? Everywhere I see it, the instructions state to set `INFLUXD_OPTS` in `/etc/default/influxdb`, not to set it at the command line.

**Comment by pauldix** [comment]
Oh, I completely overlooked that. I was troubleshooting a cluster setup problem with a customer and they were having a problem with that environment variable not getting set. I'll have to follow up and see if they were setting that file and what OS they're on.

**Comment by beckettsean** [comment]
closing issue.
