### ISSUE TITLE
verify docs on min/max timestamps

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#400]
See https://github.com/influxdb/influxdb/issues/4461#issuecomment-148632634, which disagrees with my black box testing some months ago, which produced the numbers on https://influxdb.com/docs/v0.9/troubleshooting/frequently_encountered_issues.html#querying-outside-the-min-max-time-range

**Comment by gunnaraasen** [comment]
The min/max mentioned in that blog post are the boundary limits the internal engine can store. It seems the min/max able to be queried via the query language may be a slightly smaller number.
