### ISSUE TITLE
SHOW MEASUREMENTS now allows regex matching

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#410]
https://github.com/influxdb/influxdb/pull/4501

Need to update the schema exploration page.

**Comment by beckettsean** [comment]
fixed.

**Comment by beckettsean** [comment]
`SHOW MEASUREMENTS WITH MEASUREMENT =~ /cpu.*/`

**Comment by rkuchan** [comment]
Closed in favor of: https://github.com/influxdb/docs.influxdata.com/issues/46
