### ISSUE TITLE
[new page] How Do I?

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#421]
This is more of a real FAQ page, to complement the FEI page. A few things to start with:

- how do I find how many series are in a measurement?
- how do I find the most recent point in a measurement/series?
- how do I find the first point in a measurement/series?
- how do I find the rate of change in a counter metric?

I'm not totally sure what this page needs to be, yet. Let's start gathering ideas here to see if we have a FAQ for the docs or just a series of Help Center articles.

**Comment by beckettsean** [comment]
@gunnaraasen @rkuchan @rossmcdonald @pauldix @otoolep @mjdesa @jackzampolin 

Ideas for more FAQ entries? Should be something of general interest to those getting started with InfluxDB, and something not already addressed in the docs (no "how do I set up a cluster?" but maybe "how do I test my cluster is healthy?")

**Comment by otoolep** [comment]
Big topic. I will keep it in mind as I encounter issues.

**Comment by beckettsean** [comment]
too vague for now.
