### ISSUE TITLE
update write pages to reflect new partial batch success writes

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#436]
From https://github.com/influxdb/influxdb/pull/4587:

"HTTP line protocol handler will now write all successfully parsed points instead of failing the entire batch if one failed. When some points fail to parse and the remaining are written successfully, the endpoint returns a partial write error with the failed lines in the response. This makes the behavior more consistent with the other inputs."

**Comment by shanielh** [comment]
+1 on this one, I couldn't find documentation on this. And the only documentation is done in a "side" issue.

**Comment by beckettsean** [comment]
Add to "Write a Batch of Points with `curl`" on https://influxdb.com/docs/v0.9/write_protocols/write_syntax.html
