### ISSUE TITLE
FAQ - how to tell the server is alive

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#438]
https://github.com/influxdb/influxdb/issues/4595

Also should cover how to tell if the server is live for writes or queries. Maybe not always be true even if `/ping` returns a good response?

**Comment by otoolep** [comment]
I am working on improving this endpoint - standby.

**Comment by otoolep** [comment]
@beckettsean -- once this merges, I suggest we update the docs. With this change the ping can be instructed to only return when there is a leader available, which is a pretty good way to know the cluster is ready to go.

**Comment by beckettsean** [comment]
@otoolep from reading the PR it looks like there are now two ping options:

`curl -G 'http://localhost:8086/ping'` which returns a 204 with the `X-Influxdb-Version` header property provided that the HTTP listener is alive.

`curl -G 'http://localhost:8086/ping?wait_for_leader=1s'` which does the same but won't return a 204 unless there's a valid raft leader.

It looks like the time parameter is parsed, so I could also issue `/ping?wait_for_leader=10s` and it would wait up to 10 seconds to verify there is a raft leader? What about HTTP timeouts, does the setting override other connection timeouts? I assume not, just want to make sure for the docs.

What's the use case for `/ping?wait_for_leader=10s` vs `/ping?wait_for_leader=1s`? Clusters with > 500ms latency?

**Comment by beckettsean** [comment]
@otoolep your comments on https://github.com/influxdb/influxdb/issues/4595#issuecomment-151958860 answer most of my questions, thanks!

Just wondering about the HTTP timeouts. If I set `wait_for_leader=20m` presumably the connection times out at 30 seconds or 300 seconds or whatever the HTTP timeout is for influxd?

**Comment by otoolep** [comment]
I have not tested very long timeouts, but I suspect any underlying HTTP timeout might kick in before a very long timeout, as you suggest.

**Comment by otoolep** [comment]
As for any particular `wait_for_leader` timeout vs. another, I agree that 60s versus 10m is not a big difference (the cluster is probably stalled for some reason). But 5-30 seconds might be the kind of thing would might do while waiting for a node to come up and join.

**Comment by otoolep** [comment]
FWIW, I do see that the system doesn't even start the HTTP handler service until the node has booted up quite far, so "connection refused" may also come back, even though the node has started. So this endpoint in particularly useful for monitoring nodes passively, to ensure everything is healthy.
