### ISSUE TITLE
Update docs for UDP listener

### ISSUE THREAD

**Issue by sparrc** [influxdb/influxdb.com#454]
Once these PRs are merged

https://github.com/influxdb/influxdb/pull/4676
https://github.com/influxdb/influxdb/pull/4681

udp, graphite & collectd listeners have new defaults for:
```
batch-size = 1000 -> 5000
batch-pending = 5 -> 10
```

They also have new arguments for the udp read buffer:

udp & collectd
```
read-buffer = 8388608 # (8*1024*1024)
```

graphite:
```
udp-read-buffer = 8388608 # (8*1024*1024)
```

I can update these once the PRs are merged, just wanted to track it somewhere

**Comment by otoolep** [comment]
We shouldn't update the docs. Instead we should update the READMEs within each service. Our docs already link to the READMEs.

**Comment by otoolep** [comment]
I'm going to close this because I don't think it's what we want.

**Comment by sparrc** [comment]
oh, maybe just the UDP plugin then: https://influxdb.com/docs/v0.9/write_protocols/udp.html

**Comment by otoolep** [comment]
OK, fair enough. We do have a README for UDP which will need updating too.

**Comment by sparrc** [comment]
we should add this to the website too, from the UDP input README:



## A note on UDP/IP OS Buffer sizes

Some OSes (most notably, Linux) place very restricive limits on the performance
of UDP protocols. Recent versions of FreeBSD, OSX, and Windows do not have this
problem. It is _highly_ recommended that you increase these OS limits to
8MB before trying to run large amounts of UDP traffic to your instance.

### Linux
Check the current UDP/IP buffer limit by typing the following commands:

```
sysctl net.core.wmem_max
sysctl net.core.rmem_max
```

If the values are less than 8388608 bytes you should add the following lines to the /etc/sysctl.conf file:

```
net.core.wmem_max=8388608
net.core.rmem_max=8388608
```

Changes to /etc/sysctl.conf do not take effect until reboot.  To update the values immediately, type the following commands as root:

```
sysctl -w net.core.wmem_max=8388608
sysctl -w net.core.rmem_max=8388608
```

### FreeBSD
Check the current UDP/IP buffer limit by typing the following command:

```
sysctl kern.ipc.maxsockbuf
```

If the value is less than 8388608 bytes you should add the following lines to the /etc/sysctl.conf file (create it if necessary):

```
kern.ipc.maxsockbuf=8388608
```

Changes to /etc/sysctl.conf do not take effect until reboot.  To update the values immediately, type the following commands as root:

```
sysctl -w kern.ipc.maxsockbuf=8388608
```
