### ISSUE TITLE
fix mis-statement on storage engine page

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#467]
From https://github.com/influxdb/influxdb/issues/4734#issuecomment-155876205, we need to remove that statement from the storage engine page.

**Comment by beckettsean** [comment]
@pauldix you wrote the most recent updates to that page, I believe. Can you perhaps rework it to remove the incorrect term?

https://github.com/influxdb/influxdb.com/blob/master/content/docs/v0.9/concepts/storage_engine.md

**Comment by pauldix** [comment]
ah yes, will do. There's currently some rework going on so I should probably just make a note of that.
