### ISSUE TITLE
document SUBSCRIBE

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#476]
https://github.com/influxdb/influxdb/pull/4375

**Comment by beckettsean** [comment]
probably a new page?

**Comment by sundarv85** [comment]
+1 I was looking for what is the data structure that the subscription will send

**Comment by beckettsean** [comment]
@sundarv85 I assume it is sending InfluxDB line protocol, but I haven't tested yet.

**Comment by sundarv85** [comment]
@beckettsean Great. Newbie to InfluxDB. Looking into it. More questions would be, would the series/measurement/tags also be sent along with it.

**Comment by beckettsean** [comment]
@sundarv85 the [line protocol](https://influxdb.com/docs/v0.9/write_protocols/write_syntax.html) includes all of those things.
