### ISSUE TITLE
Incorrect timezone in tag 'time' on version 0.9.4.2

### ISSUE THREAD

**Issue by yonger1516** [influxdb/influxdb.com#488]
[root@test201 /opt/influxdb]$ date -R
Mon, 16 Nov 2015 19:51:35 +0800
[root@test201 /opt/influxdb]$ ./influx
Connected to http://localhost:8086 version 0.9.4.2
InfluxDB shell 0.9.4.2
> use collectd
Using database collectd
> select * from cpu_value where host='db201' order by time desc limit 10;
name: cpu_value
---------------
time				host	type	type_instance	value
2015-11-16T11:51:46.081569Z	db201	percent	user		3.3690274907633544
2015-11-16T11:51:36.081638Z	db201	percent	user		2.639809833604406
2015-11-16T11:51:26.081705Z	db201	percent	user		2.593335003758457
2015-11-16T11:51:16.081553Z	db201	percent	user		2.660073856168241
2015-11-16T11:51:06.081548Z	db201	percent	user		2.567474481808504

========================
My machine's timezone is CST(UTC+8), but the value of 'time' seems UTC+0, they have 8 hours gap.(db201,test201 are the same machine)

**Comment by rossmcdonald** [comment]
@yonger1516 Currently InfluxDB only supports time in UTC, there is a feature request to support timezones that you can follow here:

https://github.com/influxdb/influxdb/issues/2074

**Comment by yonger1516** [comment]
why my query is error?
> select mean(value) from cpu_value where time >= today() group by time(10m) time_zone(PST);
ERR: error parsing query: found ), expected SELECT, DELETE, SHOW, CREATE, DROP, GRANT, REVOKE, ALTER, SET at line 1, char 89

I don't find any guide about 'time_zone' in official docs.

**Comment by otoolep** [comment]
There is no support for the keyword `time_zone`.

**Comment by yonger1516** [comment]
So that means issue 'https://github.com/influxdb/influxdb/issues/2074' is a plan and no implementation in this release ?

**Comment by otoolep** [comment]
Yes.

**Comment by beckettsean** [comment]
@yonger1516 if an issue is open, then it has not been developed. Issues that are closed by a pull request have been implemented.

**Comment by yonger1516** [comment]
I've got. Thank you .
