### ISSUE TITLE
Latest source RPM still pointing to 0.8.8

### ISSUE THREAD

**Issue by agoraphobia** [influxdb/influxdb.com#50]
The latest SRPM listed https://s3.amazonaws.com/influxdb/ points to https://s3.amazonaws.com/influxdb/influxdb-latest.src.tar.gz which is still on version 0.8.8. This seems to be the case for several other of the latest build packages.

**Comment by gunnaraasen** [comment]
The `latest` builds are only available for amd64 deb and x86 rpm at the moment. We'll have a new build server (influxdb/influxdb#3074) soon and will update the rest of the latest builds when it's set up.

**Comment by gunnaraasen** [comment]
With the new build server running, `latest` releases are deprecated in favor of `nightly` builds and builds where the version is explicitly stated. The download links for the current version are listed on the [downloads page](https://influxdb.com/download/index.html).
