### ISSUE TITLE
Better documentation around collectd + InfluxDB and Telegraf

### ISSUE THREAD

**Issue by jginfluxdata** [influxdb/influxdb.com#501]
Please add to the docs:

* How to configure collectd to send data to InfluxDB
* How to configure collectd in the InfluxDB Managed Hosting environment
* Documentation about the native collectd plugin

**Comment by beckettsean** [comment]
regarding the third one, https://influxdb.com/docs/v0.9/write_protocols/collectd.html now links to https://github.com/influxdb/influxdb/blob/master/services/collectd/README.md, which is sufficient.
