### ISSUE TITLE
Influx CLI doesn´t accept INSERT 

### ISSUE THREAD

**Issue by PedroGVL** [influxdb/influxdb.com#506]
If I initiate the console with Influx CLI and I write:

Connected to http://localhost:8086 version 0.9.0-rc28
InfluxDB shell 0.9.0-rc28
> create database sample_db

> use sample_db
Using database sample_db

> insert mycolection value=2
ERR: error parsing query: found INSERT, expected SELECT, DELETE, SHOW, CREATE, DROP, GRANT, REVOKE, ALTER, SET at line 1, char 1

With the commando CURL fail again:

user@host> curl -X POST 'http://localhost:8086/write?db=sample_db' --data-binary 'mycolection value=2'
{"error":"invalid character 'm' looking for beginning of value"}

NOTES:
- In September I migrated from v.0.8 to  v.0.9.0-rc28
- Most of my metrics are sended as Influx 0.8 and still works:
    curl XPOST 'http://localhost:8086/write' -d {"database":xxx "retentionPolicy": .... }
- I noticed that 90% of this "inserts" are in database (10% are lost) althouth command 'curl' responses code 200 (OK) for all, for this reason I´m analyzing the problem.

Any advice?

**Comment by beckettsean** [comment]
Upgrade to a newer version. The `insert` command was added as part of 0.9.2, I believe. There is very little reason to run anything but the latest stable release if you are using the 0.9 line.
