### ISSUE TITLE
Config file location

### ISSUE THREAD

**Issue by ajw2060** [influxdb/influxdb.com#508]
Hi guys,

The documentation suggests the following as the location of the config file.
   /etc/influxdb/influxdb.generated.conf

The default appears to be as follows
  /etc/opt/influxdb/influxdb.conf

Perhaps the documentation could be updated to show this default location.

Thanks.

**Comment by rossmcdonald** [comment]
@ajw2060 Thanks for letting us know. 

The default location was changed with v0.9.5 (released a few days ago) from `/etc/opt/influxdb` to `/etc/influxdb` (full information [here](https://github.com/influxdb/influxdb/blob/0.9.5/CHANGELOG.md#release-notes)). We are in the process of migrating the docs to point to the correct directories, though, so there are still some mis-matched areas where old directories are used with new ones (like in this instance). Everything should be fixed within the next couple of days, though. Sorry for the confusion!
