### ISSUE TITLE
update database creation and retention policy docs

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#516]
Once https://github.com/influxdb/influxdb/pull/4866 is merged.

**Comment by beckettsean** [comment]
https://github.com/influxdb/influxdb/pull/4866 is merged so let's get the docs for `CREATE DATABASE` updated for the 0.9.6 release. Might need to update the retention policy page with a note that the defaults can be altered when making the db.

I believe this comment has the final syntax: https://github.com/influxdb/influxdb/pull/4866#issuecomment-159755462

**Comment by rkuchan** [comment]
Solved by: https://github.com/influxdb/docs.influxdata.com/pull/73
