### ISSUE TITLE
[Documentation] - Breaking change for Clustering path

### ISSUE THREAD

**Issue by JulienChampseix** [influxdb/influxdb.com#519]
Hi Team,

Due the breaking change on 0.9.5 about all influxdb path (as mentionned there https://github.com/influxdb/influxdb/blob/master/CHANGELOG.md) , the clustering docs is not good anymore.

is it possible to update it :
https://influxdb.com/docs/v0.9/guides/clustering.html

Maybe help from @beckettsean for have it up to date will be required.

Thanks,
Julien.

**Comment by rossmcdonald** [comment]
@JulienChampseix The paths were actually fixed with #514, which was pushed late yesterday. Let us know if you find any other incorrect locations, though.
