### ISSUE TITLE
Document INTO keyword

### ISSUE THREAD

**Issue by mkuzmin** [influxdb/influxdb.com#520]
Starting from version 0.9.5 `INTO` keyword can be used outside of continuous queries: https://github.com/influxdb/influxdb/pull/4409.

But it's still unclear how to use this feature.

I was able to make two-step filtering with queries like these:
```
SELECT last(size) INTO temp FROM vm GROUP BY hostname
SELECT sum(last) FROM temp
```
But here are two questions:
1) how to join them into a single query? Semicolon does not work by some reason.
2) I'm using `temp`, but what does this syntax mean? It is some kind of a local variable? Is it performant and safe to use on a large number of queries in Grafana?

Thanks.

**Comment by beckettsean** [comment]
> 1) how to join them into a single query? Semicolon does not work by some reason.

This is not possible. Semicolon will run them consecutively, but there is no support yet for nested queries.

> 2) I'm using temp, but what does this syntax mean? It is some kind of a local variable? Is it performant and safe to use on a large number of queries in Grafana?

`temp` is another measurement, just like `vm`. It is not a variable, the points are being written back into the database through the normal write path. The values persist in `temp` just like the values persist in `vm`.

**Comment by beckettsean** [comment]
add to Data Exploration page

**Comment by rkuchan** [comment]
Closed in favor of https://github.com/influxdb/docs.influxdata.com/issues/32
