### ISSUE TITLE
Tool for data migration from 0.9.4 to 0.9.5

### ISSUE THREAD

**Issue by kureikain** [influxdb/influxdb.com#521]
Do we have any tools to migrate 0.9.4 data to 0.9.5? I found a thread on Gmail saying about a migratool that is in development but I cannot found any information hence this issue to track it.

**Comment by beckettsean** [comment]
There is no need to do anything to migrate data. What was discussed on the mailing list was a migration tool from the existing `b1/bz1` storage engine to the new `tsm1` storage engine, which was originally planned for 0.9.5. The `tsm1` storage engine will require migration, but it is not the default with 0.9.5 so the migration tool is not yet required. In addition, `b1/bz1` shards can co-exist in the same database with `tsm1` files. Even if you want to use the new `tsm1` engine with 0.9.5, you can do so without migrating any existing `b1/bz1` shards, and the data in those existing `b1/bz1` shards will still be available for queries.
