### ISSUE TITLE
Update all docs to point to new config file paths

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb.com#527]
For instance here: https://influxdb.com/docs/v0.9/guides/clustering.html

**Comment by beckettsean** [comment]
dupe of https://github.com/influxdb/influxdb.com/issues/517

@pauldix can you try hard refreshing? @rossmcdonald fixed all that in https://github.com/influxdb/influxdb.com/pull/514.

If there's still an error, please point out exactly where.

**Comment by pauldix** [comment]
ah, sorry about that.
