### ISSUE TITLE
add note about mmap to FEI

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#530]
Let's add a note to the frequently encountered issues page that describes our use of `mmap` and why that can look like a memory leak, but is not.

**Comment by beckettsean** [comment]
Describe also that high series cardinality requires a lot of RAM, and that does lead to OOM issues if there's not enough on the box.

**Comment by beckettsean** [comment]
@pauldix who can help us write this up in a way that is correct and meaningful?

**Comment by pauldix** [comment]
@beckettsean: What kind of help you need? I can pitch in :)
