### ISSUE TITLE
MD5 checksum for Telegraf downloads incorrect

### ISSUE THREAD

**Issue by robinroestenburg** [influxdb/influxdb.com#539]
The md5sum for the v0.2.2 Standalone Binary download as listed on https://influxdb.com/download/index.html is incorrect. I calculate it as being: f78766979e97f2dcc8afd050ca7b7c72

I can confirm that is incorrect for the deb package as well, also see this (closed) issue on Telegraf repo: https://github.com/influxdb/telegraf/issues/384

They weren't changed when bumping the version, see commits:
- 0.2.3: https://github.com/influxdb/influxdb.com/commit/74429bf6989b90be7072c1bc32c9211bd51a5700
- 0.2.2: https://github.com/influxdb/influxdb.com/commit/775cb67fe98034c560e24ea143418c60b425ec6c

**Comment by beckettsean** [comment]
@rossmcdonald can you update?

**Comment by rossmcdonald** [comment]
Actually this was fixed with #534, but it doesn't look like it's been pushed yet. The changes should be made live in the next twenty minutes or so.

**Comment by robinroestenburg** [comment]
Thanks!
