### ISSUE TITLE
CREATE DATABASE .... WITH ....

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb.com#540]
The `CREATE DATABASE` command has been enhanced, with support for optional commands. This will be in 0.9.6.

https://github.com/influxdb/influxdb/pull/4866

**Comment by beckettsean** [comment]
dupe of https://github.com/influxdb/influxdb.com/issues/516

**Comment by beckettsean** [comment]
Thanks for the diligence, @otoolep, and sorry my issue title was not clear
