### ISSUE TITLE
intra-page links not working on configuration page

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#541]
https://influxdb.com/docs/v0.9/administration/config.html#reporting
and
https://influxdb.com/docs/v0.9/administration/config.html 

go to the same spot. Looks like the Hugo IDs aren't being translated somehow:

`<h2 id="reporting:c9c91c29b41257aea3a3403cc606ad99">[reporting]</h2>`

No HREF or anchor tag there...

**Comment by gunnaraasen** [comment]
Could be the update to hugo v0.15 broke something with the anchor links. I'll check.

**Comment by gunnaraasen** [comment]
Should be fixed by 4679ec04aa0228b7370aef132cc056dc241414d8
