### ISSUE TITLE
[Documentation] - Overview with bad version

### ISSUE THREAD

**Issue by JulienChampseix** [influxdb/influxdb.com#548]
Hi Team,

Page https://influxdb.com/docs/v0.9/introduction/overview.html is mentionning the wrong version.
___The current version of InfluxDB is 0.9.4.1___

Thanks.
Julien.

**Comment by rossmcdonald** [comment]
@JulienChampseix Thanks for letting us know. We are pushing a new version of the documentation later today that will include a fix for this.
