### ISSUE TITLE
Running `SHOW STATS` kills influxd

### ISSUE THREAD

**Issue by mjdesa** [influxdb/influxdb.com#55]
Running the `SHOW STATS` command from [Server Monitoring](https://influxdb.com/docs/v0.9/query_language/stats_diags.html) page kills influxd.

**Comment by beckettsean** [comment]
@mjdesa did you remove the pages from the docs for now?

**Comment by mjdesa** [comment]
@sean I thought I did, but it seems like its still coming up locally for me.


—

**Comment by mjdesa** [comment]
Closing issue in favor of [68](https://github.com/influxdb/influxdb.com/issues/68)
