### ISSUE TITLE
query returning no data, even though I definitely placed data into db

### ISSUE THREAD

**Issue by bigKS** [influxdb/influxdb.com#554]
Hi,

I'm getting no data returned (tried CLI, and direct GET using CURL and the golang v2 client api... all 3 methods) even though I wrote points/series into a db (see the "show series" output for proof? that there was data written):

```
[ksengal@csdev-ksengal influxdb]$ influx
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 0.9.5.1
InfluxDB shell 0.9.5.1
> show databases
name: databases
---------------
name
systemstats
cs

> use cs
Using database cs
> show series
name: cpu_usage
---------------
_key			cpu
cpu_usage,cpu=cpu-total	cpu-total


name: fakeMeasurementName
-------------------------
_key										fakeTagLabel1	fakeTagLabel2
fakeMeasurementName,fakeTagLabel1=fakeTagValue1,fakeTagLabel2=fakeTagValue2	fakeTagValue1	fakeTagValue2

> select * from fakeMeasurementName
>

CurlGET:

[ksengal@csdev-ksengal influxdb]$ curl -G 'http://localhost:8086/query' --data-urlencode "db=cs" --data-urlencode "q=SELECT * FROM fakeMeasurement"
{"results":[{}]}
```

How do I debug this further?  As far as I know, points without fields are impossible to create?

HOW did I write this into DB? using the "v2" golang client api... part of the code:
```
106     // specify tags and fields to create a point
107     tags := map[string]string{"fakeTagLabel1": "fakeTagValue1", "fakeTagLabel2": "fakeTagValue2"}
108     fields := map[string]interface{}{
109         "fakeFieldLabel1": 2032.23,
110         "fakeFieldLabel2": 23234.2,
111     }
112     point, err := influx.NewPoint("fakeMeasurementName", tags, fields, time.Now())

116 
117     // create second point, which only differs in the value of the fields
118     fields = map[string]interface{}{
119         "fakeFieldLabel1": 1.2,
120         "fakeFieldLabel2": 2.3,
121     }
122     point2, err := influx.NewPoint("fakeMeasurementName", tags, fields, time.Now())
```

(Above creates 2 points, which then you add to a "batch" and write via an HTTPclient ).
( Yes, in real code I'm checking "err" returned from all methods against nil )

Any special debug commands and such that I can use to investigate this deeper?

**Comment by bigKS** [comment]
The influx CLI steps above got marked up in an unintended way, so I'll paste it again here with the prompt modified to %>:

[ksengal@csdev-ksengal influxdb]$ influx
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 0.9.5.1
InfluxDB shell 0.9.5.1
%> show databases
name: databases
---------------
name
systemstats
cs

%> use cs
Using database cs
%> show series
name: cpu_usage
---------------
_key			cpu
cpu_usage,cpu=cpu-total	cpu-total


name: fakeMeasurementName
-------------------------
_key										fakeTagLabel1	fakeTagLabel2
fakeMeasurementName,fakeTagLabel1=fakeTagValue1,fakeTagLabel2=fakeTagValue2	fakeTagValue1	fakeTagValue2

%> select * from fakeMeasurementName
%>

**Comment by bigKS** [comment]
it's not (via cli) even possible to insert a field-less point

%> insert ABC,a=3,b=4 y=3,z=6 1450322400702183477
%> insert ABC,a=3,b=4  1450322400702183477
ERR: unable to parse 'ABC,a=3,b=4  1450322400702183477': invalid field format

**Comment by beckettsean** [comment]
closing in favor of https://github.com/influxdb/influxdb/issues/5155
