### ISSUE TITLE
directory links don't automatically load index.html

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#60]
This appears to be related to the CloudFlare implementation recently done to support SSL.

influxdb.com/docs doesn't resolve to influxdb.com/docs/index.html but instead to an XML manifest of the S3 bucket contents.

See influxdb/influxdb#3101 for more

**Comment by gunnaraasen** [comment]
Looks like CloudFront will not resolve to index.html on subfolders when using an S3 bucket as the origin.

The CloudFront distribution needs to point to a custom origin for an S3 bucket so the S3 web distribution and routing rules apply.

**Comment by gunnaraasen** [comment]
This is now fixed.
