### ISSUE TITLE
some pages still reference JSON API for writes

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#61]
Inspired by https://github.com/influxdb/influxdb/issues/3100, partially fixed by #48 but should be updated to the line protocol.

**Comment by mjdesa** [comment]
should be fixed by [this](https://github.com/influxdb/influxdb.com/commit/c9594183cf3807747ac24c552e1050ea9431ed7c)

**Comment by beckettsean** [comment]
fixed by #128, already merged. Closing issue
