### ISSUE TITLE
publish a list of reserved words in InfluxQL

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#66]
What strings must be double-quoted when used as identifiers. E.g. https://github.com/influxdb/influxdb/issues/3110, https://github.com/influxdb/influxdb/issues/3119

**Comment by mjdesa** [comment]
Do we need something more comprehensive than what in the influxql spec?

**Comment by gunnaraasen** [comment]
Keeping it in the InfluxQL spec is fine. We can put it in a more prominent place if people report having trouble finding them in the spec.

@mjdesa We should also synchronize what's in the InfluxQL spec with what's actually reserved in the code. I can go through that (unless you've already checked).

**Comment by mjdesa** [comment]
@gunnaraasen haven't checked. You're probably more well equipped than I am to go through whats actually reserved in the code.

**Comment by beckettsean** [comment]
Let's put it on the troubleshooting page: content/docs/v0.9/guides/troubleshooting.md

I've unlinked the page from the right nav because I didn't finish it, but

**Comment by beckettsean** [comment]
also already present on https://influxdb.com/docs/v0.9/query_language/spec.html but let's make it easier to find by referencing/duplicating it on troubleshooting

**Comment by mjdesa** [comment]
[128](https://github.com/influxdb/influxdb.com/pull/128)

**Comment by beckettsean** [comment]
closed by #128.
