### ISSUE TITLE
document build system improvements

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#76]
Nightly builds: how to get, how to install for Ubuntu, RHEL, OS X.

TGZ: how to get, what's in it?

**Comment by otoolep** [comment]
It's available at the same location as the RPM and debian packages. E.g.

https://s3.amazonaws.com/influxdb/influxdb_nightly_x86_64.tar.gz

It is the `/etc` and `/opt` trees tarred up. Let me know if need more information.

**Comment by beckettsean** [comment]
@gunnaraasen I think the existing downloads page covers this. Yes?

**Comment by gunnaraasen** [comment]
There's no info on the download page about `influxdb_nightly_x86_64.tar.gz` even though we make it available on S3. Not sure if that's something we want to add to the download page.

**Comment by beckettsean** [comment]
I think we should mention it with some warnings: "These binaries were compiled for x86 on Ubuntu and then simply tar'd up. They may or may not work for your particular distro. Please use the pre-built packages unless you know what you are doing."

**Comment by beckettsean** [comment]
closing this in favor of https://github.com/influxdb/influxdb.com/issues/267
