### ISSUE TITLE
better language library list

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#77]
Here's a good model: https://docs.docker.com/reference/api/remote_api_client_libraries/

**Comment by mjdesa** [comment]
Here's a quick version of what I came across

# Javascript/Node

[https://github.com/node-influx/node-influx](https://github.com/node-influx/node-influx)

[https://github.com/collectors/node-influxdb-udp](https://github.com/collectors/node-influxdb-udp)

# PHP

[https://github.com/crodas/InfluxPHP](https://github.com/crodas/InfluxPHP)

[https://github.com/corley/influxdb-php-sdk](https://github.com/corley/influxdb-php-sdk)


# .NET

[https://github.com/ziyasal/InfluxDB.Net](https://github.com/ziyasal/InfluxDB.Net)


# Haskell

[https://github.com/maoe/influxdb-haskell](https://github.com/maoe/influxdb-haskell)


# Rails

[https://github.com/palkan/influxer](https://github.com/palkan/influxer)


# PERL

[https://github.com/hirose31/p5-InfluxDB](https://github.com/hirose31/p5-InfluxDB)


# INFLUX AUTHORED

[https://github.com/influxdb/influxdb-python](https://github.com/influxdb/influxdb-python)

[https://github.com/influxdb/influxdb-ruby](https://github.com/influxdb/influxdb-ruby)

[https://github.com/influxdb/influxdb-java](https://github.com/influxdb/influxdb-java)

[https://github.com/influxdb/influxdb-rails](https://github.com/influxdb/influxdb-rails)

[https://github.com/influxdb/influxdb-scala](https://github.com/influxdb/influxdb-scala)
