### ISSUE TITLE
add examples of queries with absolute time 

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#87]
E.g. more `select * from foo where time > 12345678s` instead of `where time > now() - 2d`

**Comment by mjdesa** [comment]
So I added a little more on one page. Should I go through the entire docs and add more examples absolute time?

**Comment by beckettsean** [comment]
@mjdesa yes, please add more throughout. I'd say if there is more than one query with a `WHERE time` clause on the page then at least one example should be absolute time.

**Comment by mjdesa** [comment]
Fixed by https://github.com/influxdb/influxdb.com/pull/167
