### ISSUE TITLE
add query return syntax to query syntax page

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#88]
We need to provide the CLI column return syntax, both the framework and actual examples of the returns for the queries on the page.

Describe why `name` is used when `measurement` is usually more specific. Show multiple field returns, multiple tag returns, returns from `show databases`, `show series`, `show measurements`, `show tag values`, etc.

**Comment by mjdesa** [comment]
why is name used instead?

**Comment by beckettsean** [comment]
Regan, when you get to this page as part of the checking, be sure to add some query returns as you've been doing elsewhere. Thanks!

**Comment by jackzampolin** [comment]
Fixed by: https://github.com/influxdb/influxdb.com/pull/343
