### ISSUE TITLE
Too many people are emailing contact@ instead of support@

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb.com#91]
Let's find out why and try to fix it, either by labeling contact@ better or by hiding it more.

**Comment by beckettsean** [comment]
Note that we want people to email contact@ if they have questions for InfluxDB the company. We want them to email support@ if they want support for the database, telegraf, etc. I'm not sure why so many people recently have been emailing contact@ with questions meant for support@.

**Comment by mjdesa** [comment]
I think this may be the source of the issue:

![screen shot 2015-07-02 at 11 00 42 am](https://cloud.githubusercontent.com/assets/1477539/8483991/a9b99268-20a9-11e5-878f-399bc357c465.png)

The contact page only references the `contact@` email. I actually cant even find the support email any where on the site.

**Comment by mjdesa** [comment]
there's one reference on the community page

**Comment by gunnaraasen** [comment]
The "Contact us for details button" on the support page sends emails to contact@. Not sure if that's where people are finding the contact@ email address. We could add the support@ address to the contact page.
